version: '3'
services:
  app:
    container_name: 0-deep-learning
    build: .
    volumes:
      - $PWD:/srv/
    environment:
      - TZ=Asia/Tokyo
    tty: true
    command: bash
    working_dir: /srv
